DatabasePersistenceManager don t log exceptions for each statement when a connection needs to be reestablished
This is just a cosmetic fix when reestablishConnection is called in DatabasePersistenceManager all the statements are closed but if an error occurs two exceptions are logged for each statement. Since reestablishConnection is already called when an exception has been caught and its only purpose is to cleanup an existing connection and to reopen a new one is pretty common that the connection is already not valid and that each statement close will throw an exception. For example if the connection has been broken due to a network problem DatabasePersistenceManager will log 40 exceptions 2 for each statement before trying to establish a connection and that s pretty annoying expecially if you use a mail appender for log4j.... simple patch that simply remove the logException at statement close during reestablishConnection Committed the patch in revision 511478 with a minor comment change mentioned this issue to explain the code . Thanks for the improvement idea and the patch I tagged this for the 1.3 release instead of 1.2.3 since the issue is not really a bug that would need an immediate fix.
