CachingHttpClient.execute does not catch the IOException thrown by HttpCache.getCacheEntry 
The IOException caused by the HttpCache is not caught and thus the whole http request fails. I would expect the response to be retrieved from the backend when the cache fails for some reason.I would actually call this a bug. The attached patch fixes this issue now cache IOExceptions are caught logged at WARN and then ignored hooray HTTP protocol robustness to failure . This patch is contributed to the ASF with the permission of my employer. Patch checked in. Many thanks Jon. Oleg
