Occasional testDataStoreGarbageCollection test failures
In the past few days our Hudson build started failing every now and then with the following jackrabbit-core test failure javax.jcr.NoSuchWorkspaceException security at org.apache.jackrabbit.core.RepositoryImpl.getWorkspaceInfo RepositoryImpl.java 786 at org.apache.jackrabbit.core.RepositoryImpl.getSystemSession RepositoryImpl.java 985 at org.apache.jackrabbit.core.RepositoryImpl.getSecurityManager RepositoryImpl.java 471 at org.apache.jackrabbit.core.RepositoryImpl.login RepositoryImpl.java 1496 at org.apache.jackrabbit.core.TransientRepository.login TransientRepository.java 380 at org.apache.jackrabbit.commons.AbstractRepository.login AbstractRepository.java 123 at org.apache.jackrabbit.core.data.DataStoreAPITest.testDataStoreGarbageCollection DataStoreAPITest.java 55 Looking at the code it seems the repository already exists when the test is started. I would like to verify this really is the case. I don t think this will fix the bug so I leave it open for now.Maybe my change did fix the problem Or it was not a problem within the test case. Please re-open if the problem still occurs.
