<!-- 
RSS generated by JIRA (5.2.8#851-sha1:3262fdc28b4bc8b23784e13eadc26a22399f5d88) at Sat Jul 27 05:48:24 UTC 2013

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://issues.apache.org/jira/si/jira.issueviews:issue-xml/JCR-1572/JCR-1572.xml?field=key&field=summary
-->
<rss version="0.92" >
<channel>
    <title>ASF JIRA</title>
    <link>https://issues.apache.org/jira</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>5.2.8</version>
        <build-number>851</build-number>
        <build-date>26-02-2013</build-date>
    </build-info>

<item>
            <title>[JCR-1572] DbDataStore connection does not always reconnect</title>
                <link>https://issues.apache.org/jira/browse/JCR-1572</link>
                <project id="10591" key="JCR">Jackrabbit Content Repository</project>
                        <description>If a DbDataStore connection is closed due to an error all subsequent addRecord calls will fail with &amp;#39;connection has been closed and autoReconnect == false&amp;#39;&lt;br/&gt;
&amp;nbsp;after getRecord is called and the connection is reconnected addRecord will succeed.&lt;br/&gt;
&lt;br/&gt;
the connection should be validated before setting autoReconnect = false or on retrieval from the pool.</description>
                <environment></environment>
            <key id="12395229">JCR-1572</key>
            <summary>DbDataStore connection does not always reconnect</summary>
                <type id="1" iconUrl="https://issues.apache.org/jira/images/icons/issuetypes/bug.png">Bug</type>
                                <priority id="3" iconUrl="https://issues.apache.org/jira/images/icons/priorities/major.png">Major</priority>
                    <status id="6" iconUrl="https://issues.apache.org/jira/images/icons/statuses/closed.png">Closed</status>
                    <resolution id="1">Fixed</resolution>
                                <assignee username="tmueller">Thomas Mueller</assignee>
                                <reporter username="moshe@egis-software.com">Moshe Immerman</reporter>
                        <labels>
                    </labels>
                <created>Fri, 2 May 2008 23:44:03 +0100</created>
                <updated>Wed, 21 Jan 2009 09:32:14 +0000</updated>
                    <resolved>Thu, 2 Oct 2008 16:28:21 +0100</resolved>
                                            <fixVersion>core 1.4.8</fixVersion>
                <fixVersion>1.5</fixVersion>
                                <component>jackrabbit-core</component>
                        <due></due>
                    <votes>1</votes>
                        <watches>2</watches>
                                                    <comments>
                    <comment id="12594157" author="tmueller" created="Mon, 5 May 2008 08:08:00 +0100"  >&amp;gt; If a DbDataStore connection is closed due to an error &lt;br/&gt;
What kind of error did occur? I don&amp;#39;t think the DbDataStore should automatically re-try forever by default.</comment>
                    <comment id="12594451" author="moshe@egis-software.com" created="Tue, 6 May 2008 04:13:31 +0100"  >a MySQL max_packet_size error. I agree it shouldn&amp;#39;t retry forever, but a addRecord operation should not fail only because the previous addRecord failed. I believe an option to execute a simple query before returning a connection from the pool should be sufficient. </comment>
                    <comment id="12594498" author="tmueller" created="Tue, 6 May 2008 08:09:19 +0100"  >Hi,&lt;br/&gt;
&lt;br/&gt;
I think it makes sense to solve the original problem instead of trying to work around it.&lt;br/&gt;
&lt;br/&gt;
I was searching for &amp;quot;MySQL max_packet_size error&amp;quot; and found this: &lt;br/&gt;
&lt;a href=&quot;http://www.mysqltalk.org/maxpacketsize-info-vt112883.html&quot;&gt;http://www.mysqltalk.org/maxpacketsize-info-vt112883.html&lt;/a&gt;&lt;br/&gt;
&lt;br/&gt;
&amp;quot;I had to set this an actually it is a setting in the server side mysql config file like this:&lt;br/&gt;
set-variable = max_allowed_packet=16M &amp;quot;&lt;br/&gt;
&lt;br/&gt;
&amp;quot;This is a known bug (check &lt;a href=&quot;http://bugs.mysql.com/)&quot;&gt;http://bugs.mysql.com/)&lt;/a&gt; that was a regression in 3.0. It is fixed (to be released in 3.0.9)&amp;quot;&lt;br/&gt;
&lt;br/&gt;
What version of MySQL (server and JDBC client) do you use? How big was your largest object? Did you set max_allowed_packet? When I tested it, it worked without any special settings. I have tested with MySQL 5.0.27-community-nt on Windows XP (2007-12-11) and found out that the objects must fit in memory. It would be great if this problem could be solved as well.&lt;br/&gt;
</comment>
                    <comment id="12594566" author="moshe@egis-software.com" created="Tue, 6 May 2008 13:20:57 +0100"  >Hi, &lt;br/&gt;
The biggest file is whatever the user wants to upload (upto GB&amp;#39;s) ,  This occurs with  a CommunicationException as well so changing the max_packet_size will have no affect when the link goes down temporarily. allowing this option will greatly improve the robustness of Jackrabbit. A check-valid-sql options is quite common for connection pools and can be found in commons-dbcp and jboss datasource, etc..  If you agree with the fix I am prepared to submit a patch for it.</comment>
                    <comment id="12595479" author="tmueller" created="Fri, 9 May 2008 08:11:50 +0100"  >Hi,&lt;br/&gt;
&lt;br/&gt;
Validation is a good idea, what about a query of the form SELECT * FROM DATASTORE WHERE 1=0. What I want to avoid is hiding a real problem, so I think this validation should be optional. &lt;br/&gt;
&lt;br/&gt;
I still think it&amp;#39;s more important to understand the real problem first: why did you get a CommunicationException, why did the link go down temporarily? What version of MySQL (server and JDBC client) do you use? When I have tested it with MySQL, I found out that the objects must fit in memory. Is this the case for you as well?&lt;br/&gt;
&lt;br/&gt;
Regards,&lt;br/&gt;
Thomas</comment>
                    <comment id="12595602" author="moshe@egis-software.com" created="Fri, 9 May 2008 15:10:17 +0100"  >Hi&lt;br/&gt;
&lt;br/&gt;
&lt;br/&gt;
I agree it should be optional, I do believe objects need to fit it memory, I think the connection went down due to an internal network error.  I use MySQL 5.0 and 5.1 driver.  I will submit a patch shortly.&lt;br/&gt;
&lt;br/&gt;
Moshe&lt;br/&gt;
&lt;br/&gt;
&lt;br/&gt;
</comment>
                    <comment id="12601392" author="moshe@egis-software.com" created="Sat, 31 May 2008 15:42:00 +0100"  >an optional checkValidConnectionSql attribute can be added to DbDataStore and BundleDbPersistenceManager&lt;br/&gt;
&lt;br/&gt;
Should I refactor DatabaseFileystem, DatabaseJournal and DatabasePersistenceManager to use ConnectionRecoveryManager so that they can benefit from this change as well?</comment>
                    <comment id="12630649" author="bspies" created="Fri, 12 Sep 2008 19:29:38 +0100"  >I haven&amp;#39;t looked at the patch yet, but I am experiencing a very similar problem using Apache Derby. It is occurring because I am using Artifactory 1.3 (beta) which updates its Maven indexes using Quartz scheduled jobs that rely on Apache Jackrabbit to store/persist the data. The code path of the problem is the same--through the addRecord() method, which automatically calls setAutoReconnect(false) without checking for a valid connection. Forgive me if I am repeating the above discussion, but there are two problems here:&lt;br/&gt;
&lt;br/&gt;
1. Not checking for valid connection before setting autoReconnect(false). This seems to be happening constantly in the Artifactory jobs, since they are long-running and the connections tend to time out. Some logic equivalent to DBCP&amp;#39;s testOnBorrow() needs to be implemented.&lt;br/&gt;
2. The setAutoReconnect(false)...setAutoReconnect(true) are both inside a try-catch block. What happens here if an exception is thrown between the two calls? Since the ConnectionRecoveryManager instances are held in a pool (the Pool class), the ConnectionRecoveryManager will be returned to the pool with the autoReconnect flag = false. Assuming that execution continues after the original exception, this ConnectionRecoveryManager instance will be likely to throw another exception if a connection timeout occurs. THE SOLUTION: restore the correct flag using setAutoReconnect in the finally block.&lt;br/&gt;
&lt;br/&gt;
These should be very easy fixes to implement.&lt;br/&gt;
&lt;br/&gt;
The exception looks like this:&lt;br/&gt;
&lt;br/&gt;
[9/12/08 11:05:24:697 PDT] 0000004e SystemOut     O 2008-09-12 11:05:24,696 [WARN ] (data.db.DbDataStore :588)  - Can not insert new record&lt;br/&gt;
org.apache.jackrabbit.core.data.DataStoreException: Can not insert new record: connection has been closed and autoReconnect == false: connection has been closed and autoReconnect == false&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.data.db.DbDataStore.convert(DbDataStore.java:592)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.data.db.DbDataStore.addRecord(DbDataStore.java:295)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.value.BLOBInDataStore.getInstance(BLOBInDataStore.java:120)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.value.InternalValue.getBLOBFileValue(InternalValue.java:644)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.value.InternalValue.create(InternalValue.java:123)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.PropertyImpl.setValue(PropertyImpl.java:609)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.PropertyImpl.setValue(PropertyImpl.java:525)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.NodeImpl.setProperty(NodeImpl.java:2309)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.jcr.fs.JcrFile.fillJcrData(JcrFile.java:591)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.jcr.fs.JcrFile.setResourceNode(JcrFile.java:550)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.jcr.fs.JcrFile.&amp;lt;init&amp;gt;(JcrFile.java:80)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.jcr.fs.JcrFile.&amp;lt;init&amp;gt;(JcrFile.java:164)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.repo.index.RepoIndexerData.saveIndexFiles(RepoIndexerData.java:103)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.repo.index.IndexerManagerImpl.saveIndexFiles(IndexerManagerImpl.java:168)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.repo.index.IndexerManagerImpl$$FastClassByCGLIB$$76058b92.invoke(&amp;lt;generated&amp;gt;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:700)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:635)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.repo.index.IndexerManagerImpl$$EnhancerByCGLIB$$7cded8f3.saveIndexFiles(&amp;lt;generated&amp;gt;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.repo.index.IndexerManagerImpl.index(IndexerManagerImpl.java:137)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.repo.index.IndexerManagerImpl$$FastClassByCGLIB$$76058b92.invoke(&amp;lt;generated&amp;gt;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:700)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:635)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.repo.index.IndexerManagerImpl$$EnhancerByCGLIB$$7cded8f3.index(&amp;lt;generated&amp;gt;)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.repo.index.IndexerJob.onExecute(IndexerJob.java:25)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.artifactory.schedule.ArtifactoryJob.execute(ArtifactoryJob.java:41)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.quartz.core.JobRunShell.run(JobRunShell.java:202)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:525)&lt;br/&gt;
Caused by: java.sql.SQLException: connection has been closed and autoReconnect == false&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.persistence.bundle.util.ConnectionRecoveryManager.getConnection(ConnectionRecoveryManager.java:159)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.persistence.bundle.util.ConnectionRecoveryManager.executeStmtInternal(ConnectionRecoveryManager.java:287)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.persistence.bundle.util.ConnectionRecoveryManager.executeStmt(ConnectionRecoveryManager.java:257)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.persistence.bundle.util.ConnectionRecoveryManager.executeStmt(ConnectionRecoveryManager.java:237)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;at org.apache.jackrabbit.core.data.db.DbDataStore.addRecord(DbDataStore.java:286)&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;... 33 more&lt;br/&gt;
&lt;br/&gt;
</comment>
                    <comment id="12634424" author="tmueller" created="Thu, 25 Sep 2008 11:02:59 +0100"  >Sorry for the delay. I can now reproduce the problem, re-connect is disabled at the wrong time. I don&amp;#39;t actually see why auto-reconnect should be disabled at all: autoCommit is never disabled. I suggest to simply remove those lines:&lt;br/&gt;
&lt;br/&gt;
Index: jackrabbit/jackrabbit-core/src/main/java/org/apache/jackrabbit/core/data/db/DbDataStore.java&lt;br/&gt;
===================================================================&lt;br/&gt;
--- jackrabbit/jackrabbit-core/src/main/java/org/apache/jackrabbit/core/data/db/DbDataStore.java	(revision 698167)&lt;br/&gt;
+++ jackrabbit/jackrabbit-core/src/main/java/org/apache/jackrabbit/core/data/db/DbDataStore.java	(working copy)&lt;br/&gt;
@@ -285,7 +285,6 @@&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;TempFileInputStream fileInput = null;&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;ConnectionRecoveryManager conn = getConnection();&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;try {&lt;br/&gt;
-            conn.setAutoReconnect(false);&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;String id = null, tempId = null;&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;long now;&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;for (int i = 0; i &amp;lt; ConnectionRecoveryManager.TRIALS; i++) {&lt;br/&gt;
@@ -362,7 +362,6 @@&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;}&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;usesIdentifier(identifier);&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;DbDataRecord record = new DbDataRecord(this, identifier, length, now);&lt;br/&gt;
-            conn.setAutoReconnect(true);&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;return record;&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;} catch (Exception e) {&lt;br/&gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;throw convert(&amp;quot;Can not insert new record&amp;quot;, e);&lt;br/&gt;
&lt;br/&gt;
I tested it and it works, and I don&amp;#39;t see a reason why it shouldn&amp;#39;t. Unless somebody sees a problem I will commit it to the trunk.</comment>
                    <comment id="12636375" author="tmueller" created="Thu, 2 Oct 2008 16:28:21 +0100"  >Committed in revision 701154</comment>
                    <comment id="12659967" author="schans" created="Tue, 30 Dec 2008 22:22:36 +0000"  >Thomas,&lt;br/&gt;
&lt;br/&gt;
Could this (almost) trivial  patch also be backported to the 1.5 and 1.4 branch? This is quite a nasty bug because it leaves the repository in an error state in which no new documents can be added.&lt;br/&gt;
&lt;br/&gt;
Bart</comment>
                    <comment id="12660048" author="jukkaz" created="Wed, 31 Dec 2008 09:23:14 +0000"  >&amp;gt; Could this (almost) trivial patch also be backported to the 1.5 and 1.4 branch?  &lt;br/&gt;
&lt;br/&gt;
This fix is included in the 1.5.0 release.</comment>
                    <comment id="12660056" author="schans" created="Wed, 31 Dec 2008 10:01:31 +0000"  >Indeed it is! I somehow completely overlooked that one... My question still stands for the 1.4 branch though. Or are there no plans to release new versions of the 1.4 (core) jars?</comment>
                    <comment id="12660058" author="jukkaz" created="Wed, 31 Dec 2008 10:13:54 +0000"  >There&amp;#39;s no active plan for another 1.4.x release, but it shouldn&amp;#39;t be too much trouble to do such a release if there&amp;#39;s demand and upgrading to 1.5.0 is for some reason not an option.</comment>
                    <comment id="12663800" author="jukkaz" created="Wed, 14 Jan 2009 17:07:35 +0000"  >Scheduling for jackrabbit-core 1.4.8.</comment>
                    <comment id="12665769" author="tmueller" created="Wed, 21 Jan 2009 09:32:14 +0000"  >Committed in revision 736273 (1.4 branch)</comment>
                </comments>
                    <attachments>
                    <attachment id="12383168" name="jackrabbit1.4.patch" size="9881" author="moshe@egis-software.com" created="Sat, 31 May 2008 15:42:00 +0100" />
                    <attachment id="12383169" name="jackrabbit-trunk.patch" size="8786" author="moshe@egis-software.com" created="Sat, 31 May 2008 15:42:00 +0100" />
                </attachments>
            <subtasks>
        </subtasks>
                <customfields>
                                <customfield id="customfield_12310310" key="com.atlassian.jira.toolkit:attachments">
                <customfieldname>Attachment count</customfieldname>
                <customfieldvalues>
                    <customfieldvalue>2.0</customfieldvalue>
                </customfieldvalues>
            </customfield>
                                                                <customfield id="customfield_12310220" key="com.atlassian.jira.ext.charting:firstresponsedate">
                <customfieldname>Date of First Response</customfieldname>
                <customfieldvalues>
                    <customfieldvalue>Mon, 5 May 2008 07:08:00 +0000</customfieldvalue>

                </customfieldvalues>
            </customfield>
                                                                                                        <customfield id="customfield_12310420" key="com.pyxis.greenhopper.jira:gh-global-rank">
                <customfieldname>Global Rank</customfieldname>
                <customfieldvalues>
                    <customfieldvalue>78502</customfieldvalue>
                </customfieldvalues>
            </customfield>
                                            <customfield id="customfield_12310920" key="com.pyxis.greenhopper.jira:gh-global-rank">
                <customfieldname>Rank</customfieldname>
                <customfieldvalues>
                    <customfieldvalue>190175</customfieldvalue>
                </customfieldvalues>
            </customfield>
                                                                                    <customfield id="customfield_12310222" key="com.atlassian.jira.ext.charting:timeinstatus">
                <customfieldname>Time in Status</customfieldname>
                <customfieldvalues>
                    
                </customfieldvalues>
            </customfield>
                            </customfields>
    </item>
</channel>
</rss>